services:
  api:
    build:
      context: ../
    container_name: library-api
    command: ./infra/commands/api.sh
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    networks:
      - library-backend-tier
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: library-db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library-backend-tier


volumes:
  postgres_data:

networks:
  library-backend-tier: